include("./content/scripts/validations/validate.js");
include("./content/scripts/tasks/task_1_calculateAgeInDays.js");
include("./content/scripts/tasks/task_2_calculateAgeInSeconds.js");
include("./content/scripts/tasks/task_3_buggyCode.js");
include("./content/scripts/tasks/task_4_reversingAString.js");
include("./content/scripts/tasks/task_5_sumOf2Numbers.js");
include("./content/scripts/tasks/task_6_howManySecondsInHours.js");
include("./content/scripts/tasks/task_8_numberExistsInArray.js");
$('.alert').alert()