include("./content/scripts/common/validate.js");
include("./content/scripts/common/variables.js");
include("./content/scripts/tasks/task_1_calculateAgeInDays.js");
include("./content/scripts/tasks/task_2_calculateAgeInSeconds.js");
include("./content/scripts/tasks/task_3_buggyCode.js");
include("./content/scripts/tasks/task_4_reversingAString.js");
include("./content/scripts/tasks/task_5_sumOf2Numbers.js");
include("./content/scripts/tasks/task_7_createAdeckOfCards.js");
include("./content/scripts/tasks/task_6_howManySecondsInHours.js");
include("./content/scripts/tasks/task_8_numberExistsInArray.js");
include("./content/scripts/tasks/task_9_analyzeString.js");
include("./content/scripts/tasks/task_10_analyzeJson.js");
include("./content/scripts/tasks/task_11_equilibrium.js");
include("./content/scripts/tasks/task_12_formatDate.js");
include("./content/scripts/tasks/task_13_sentenceValue.js");
include("./content/scripts/tasks/task_14_analyzeStudentNames.js");
include("./content/scripts/tasks/task_15_largestPalindromeProduct.js");
include("./content/scripts/tasks/task_16_extractingWordsWithIngInflection.js");
$('.alert').alert()